version: '3.8'
services:
  teamhack_db:
    image: innovanon/teamhack-db
    container_name:  teamhack-db
    volumes:
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    #network_mode:    service:vpn-s1
    depends_on:
      postgres:
        condition: service_healthy
      syslog:
        condition: service_started
      #  condition:   service_healthy

